### ISSUE TITLE
Add ability to configure symfony slugify service

### ISSUE THREAD

**Issue by estahn** [cocur/slugify#105]
#104

**Comment by estahn** [comment]
@florianeckerstorfer Can your create a new version? I don't think there are any BC breaks.

**Comment by florianeckerstorfer** [comment]
I guess that it should work, but can you confirm that moving the Extension to another namespace does not break existing installations?

**Comment by estahn** [comment]
We haven't moved the extension to another namespace, have we? In either
case the extension is not directly used anyways. The bundle will be
included in the AppKernel and the extension is referenced in the bundle. If
you want to be 100% sure you can bump the major version, but I don't think
it's necessary.

**Comment by florianeckerstorfer** [comment]
You're right, I miss read something there. I will create a new version as soon as I have time.

**Comment by florianeckerstorfer** [comment]
Version 2.1.0 includes this. Thanks again for your PR.
