### ISSUE TITLE
ServiceProviderInterface not found

### ISSUE THREAD

**Issue by wesleyvicthor** [cocur/slugify#119]
hey guys, any guess why I got this error ?

I am on Silex 2 and Slugify 2.1

Fatal error: Interface 'Silex\ServiceProviderInterface' not found in /var/www/vendor/cocur/slugify/src/Bridge/Silex/SlugifyServiceProvider.php on line 28

just notice this interface is related to the silex application. the declaration I have in my codebase uses the pimple declaration. this is a version incompatibility ?

**Comment by wesleyvicthor** [comment]
urgh, seems there is a lot of missing components ```Class 'Nette\DI\CompilerExtension' not found``` is that alright ? am I missing anything ?

**Comment by florianeckerstorfer** [comment]
Slugify is not yet compatible with Silex 2.0
