### ISSUE TITLE
Core functionality for earlier PHP versions?

### ISSUE THREAD

**Issue by mortenscheel** [cocur/slugify#134]
I'm maintaining a project on PHP 5.3, and I was able to make the Slugify::slugify() method work by converting arrays to old syntax in Slugify.php.

I realize that some of the framework integrations require a newer version of PHP, but if the core functionality doesn't, why not allow earlier versions?

**Comment by florianeckerstorfer** [comment]
PHP 5.3 is out of development for so long, it is time to move on.
