### ISSUE TITLE
Arabic doesn't slugify (with / without ruleset)

### ISSUE THREAD

**Issue by nitinsurana** [cocur/slugify#137]
Hi,

`كيف حالك` slugifies to `kyf-h-lk`

**Comment by giovkanata** [comment]
What should be the right result?

**Comment by nitinsurana** [comment]
I pasted the arabic into browser url and it showed up fine, so I guess what I'm expecting is arabic instead of translated english characters.

**Comment by oozrafa** [comment]
This is the same that happens for Hebrew. So for example my final url after slugging it should be:
http://www.example.com/העמוד-שלי 
this is because all browsers in the past (many many) years support Hebrew (and Arabic) characters in the url.

In order to fix this in 'src/Slugify.php' I updated the following line of code:
from
const LOWERCASE_NUMBERS_DASHES = '/([^A-Za-z0-9]|-)+/';
to
const LOWERCASE_NUMBERS_DASHES = '/([^A-Za-z0-9א-ב]|-)+/';

I suppose a similar solution could be implemented for Arabic too.
Any suggestions about how to add this as a config option rather than manually changing the code?

**Comment by florianeckerstorfer** [comment]
You're absolutely right, we should add support to only remove characters like spaces and punctuation marks.

The problem is that the only real way to do this is to write either a list of all allowed characters or a list of all not-allowed characters. Both are a lot of work and prone to errors. If anyone wants to start working on this I would really appreciate this 😄

**Comment by oozrafa** [comment]
So isn't there a way to add an option to add custom parameters to the regex, so that if needed anyone could easily add their own additions without the need to edit the source code each time the library is updated?

**Comment by florianeckerstorfer** [comment]
You can change the default regexp super easily, using the constructor

```
$slugify = new Slugify(['regexp' => '/([^A-Za-z0-9]|-)+/']);
```

**Comment by epixilog** [comment]
For those who (like me) still have this problem, I found a solution here: 

https://medrhamnia.wordpress.com/2014/07/04/symfony2doctrineextension-creer-des-slugs-pour-les-caracteres-non-latin-arabe-particulierement/

Maybe this can also inspire the guys working on that repository (I really hope had time to do it) thanks guys for the great job you're doing!

**Comment by TnCoders** [comment]
i Have the Same Issue in Stand alone test i Have this  

`$string = 'وزيرة شؤون الشباب والرياضة';
$slugify = new \Cocur\Slugify\Slugify();
$slugify->activateRuleset('arabic');
echo $slugify->slugify($string);`

The Echo Show this : ozyr-sh-on-lshb-b-o-lry-d whish is not correct athe slug should be : 

`وزيرة-شؤون-الشباب-و-الرياضة`

That's all

I tried As per the customizeSlugEngine docs, in the model that uses Sluggable, adding:

```
public function customizeSlugEngine(Slugify $engine, $attribute)
{
    $engine->activateRuleset('arabic');
    return $engine;
}
```

And the same Problem

**Comment by TnCoders** [comment]
This issue is still open any help please ? We have the same problem what can we do ?

**Comment by florianeckerstorfer** [comment]
The problem is that Slugify currently translates into ASCII characters. We hopefully address this problem in 3.0, but no ETA

**Comment by mkwsra** [comment]
@florianeckerstorfer Any idea when you guys gonna issue version 3.0?

**Comment by chebaby** [comment]
I had the same issue with the Arabic characters (it's always the case)
So here is what i did

(**Slugify.php**)

I changed this line  :
    `const LOWERCASE_NUMBERS_DASHES = '/([^A-Za-z0-9]|-)+/';`
To :
    `const LOWERCASE_NUMBERS_DASHES = '/([^\p{Arabic}a-zA-Z0-9]+|-+)/u';`

(**DefaultRuleProvider.php**)

I also replaced the array rule correspond to the arabic to the following : 

```
       /* Arabic */
        'أ' => 'أ',
        'ب' => 'ب',
        'ت' => 'ت',
        'ث' => 'ث',
        'ج' => 'ج',
        'ح' => 'ح',
        'خ' => 'خ',
        'د' => 'د',
        'ذ' => 'ذ',
        'ر' => 'ر',
        'ز' => 'ز',
        'س' => 'س',
        'ش' => 'ش',
        'ص' => 'ص',
        'ض' => 'ض',
        'ط' => 'ط',
        'ظ' => 'ظ',
        'ع' => 'ع',
        'غ' => 'غ',
        'ف' => 'ف',
        'ق' => 'ق',
        'ك' => 'ك',
        'ل' => 'ل',
        'م' => 'م',
        'ن' => 'ن',
        'ه' => 'ه',
        'و' => 'و',
        'ي' => 'ي',
```

**Comment by the94air** [comment]
Missing some characters 
```js
const arabic = {
  "ء" : "ء",
  "ا" : "ا",
  "أ" : "أ",
  "إ" : "إ",
  "آ" : "آ",
  "ؤ" : "ؤ",
  "ئ" : "ئ",
  "ب" : "ب",
  "ت" : "ت",
  "ث" : "ث",
  "ج" : "ج",
  "ح" : "ح",
  "خ" : "خ",
  "د" : "د",
  "ذ" : "ذ",
  "ر" : "ر",
  "ز" : "ز",
  "س" : "س",
  "ش" : "ش",
  "ص" : "ص",
  "ض" : "ض",
  "ط" : "ط",
  "ظ" : "ظ",
  "ع" : "ع",
  "غ" : "غ",
  "ف" : "ف",
  "ق" : "ق",
  "ك" : "ك",
  "ل" : "ل",
  "م" : "م",
  "ن" : "ن",
  "ه" : "ه",
  "و" : "و",
  "ي" : "ي",
  "ة" : "ة",
  "ى" : "ى",
};
```
