### ISSUE TITLE
generate alias in the same language

### ISSUE THREAD

**Issue by masihfathi** [cocur/slugify#160]
i want to generate alias from your grateful code, for example i want "تست برنامه" convert to "تست-برنامه", how can i do that? and is it possible to do it with this grateful code. it is in Persian language which is nearly same as the Arabic language in the structure.

**Comment by vtxmg** [comment]
+1

**Comment by giovkanata** [comment]
As said by @florianeckerstorfer in #149 

> The current goal of this library is to convert characters into ASCII characters. There have been discussions about allowing to create UTF-8 slugs, but this is not yet implemented and planned for v3.0 (sorry, I don't have an ETA)

I don't know if already exist a library/alternative for that, but maybe @TnCoders can post his temp solution here or somewhere.

**Comment by florianeckerstorfer** [comment]
I'm closing this for now. Supporting this is planned for the future, but I need to figure out how to best implement this.
