### ISSUE TITLE
French is missing in DefaultRuleProvider

### ISSUE THREAD

**Issue by coders-market** [cocur/slugify#165]
Hi,

the French.json is available, but it isn't included in the DefaultRuleProvider. I run locally the generate-default.php and french was then added as well. 

So this should be easy to fix.

Thank you!

**Comment by gsouf** [comment]
As easy as this:

````sh
git clone https://github.com/gsouf/slugify
cd slugify/
php bin/generate-default.php
git add .
git commit -m 'include french rules in DefaultReuleProvider fix #165'
git push
````

Took me about 3 minutes, including the time to open the PR. Is this repository maintained?
