### ISSUE TITLE
Missing getName on Twig_ExtensionInterface throws error

### ISSUE THREAD

**Issue by TomCan** [cocur/slugify#169]
I'm trying to implement this in Symfony 2.8 on PHP 7.0 and running against following error:

  [Symfony\Component\Debug\Exception\FatalErrorException]
  Error: Class Cocur\Slugify\Bridge\Twig\SlugifyExtension contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Twig_ExtensionInterface::getName)

If I manually add the getName() function to the class, it doesn't throw the error.

**Comment by TomCan** [comment]
#170

**Comment by JakeFr** [comment]
Requirement for version 1 of twig was updated from 1.12 to 1.26 in order to support twig 2.
Make sure your project requires `"twig/twig": "~1.26"`
See PR #162 and [twig PR 2148](https://github.com/twigphp/Twig/pull/2148)

**Comment by florianeckerstorfer** [comment]
Fixed by #170
