### ISSUE TITLE
Spanish language

### ISSUE THREAD

**Issue by stefangeorgescu** [cocur/slugify#175]
I see Spanish mentioned in the Features:
...Polish, Romanian, Russian, Serbian, **Spanish**, Swedish, Turkish, Ukrainian...
but there is no spanish.json in Resources/rules , is there another similar language I should be using or is it just a typo and spanish is not supported yet?

**Comment by florianeckerstorfer** [comment]
Spanish rules are in `default.json`. In Slugify v1.x there was only one list of rules and we have not yet refactored Spanish rules this their own file.

**Comment by florianeckerstorfer** [comment]
If you want to provide a PR with all Spanish rules in a separate file I am happy to merge.
