### ISSUE TITLE
I had to install php7.1-mbstring

### ISSUE THREAD

**Issue by pycarlos** [cocur/slugify#184]
It is php7.1-mbstring a requirement?

If true, I can add on readme

**Comment by florianeckerstorfer** [comment]
Slugify uses `mb_strtolower()`, which should be part of the core PHP library (see http://php.net/manual/en/function.mb-strtolower.php). Which method did you use to install PHP?

**Comment by pycarlos** [comment]
I used 
```
sudo apt-get install php7.1 php7.1-cli php7.1-common
```
on Ubuntu 16.10

**Comment by florianeckerstorfer** [comment]
You're right, you need to add `--enable-mbstring` when compiling PHP. We should add this to the docs.

**Comment by wandersonwhcr** [comment]
IMHO, I think we must add `ext-mbstring` into `require` attribute from `composer.json`. This change will works with all PHP installations with `mbstring` compiled, too.

@pycarlos you must not recompile PHP, but must install `php7.1-mbstring` using `apt-get`.

```bash
sudo apt-get install php7.1-mbstring
```

**Comment by OskarStark** [comment]
Adding the ext to the composer.json is indeed the best approach to avoid further problems 👍🏻

@wandersonwhcr could you provide a PR?

**Comment by wandersonwhcr** [comment]
Of course! Just a minute ;)

**Comment by wandersonwhcr** [comment]
Done.
