### ISSUE TITLE
Notice: Undefined index: french 500 Internal Server Error - ContextErrorException

### ISSUE THREAD

**Issue by ibasaw** [cocur/slugify#187]
```
$slugger = $this->container->get('cocur_slugify');
$slugger->activateRuleSet('french');

$test = $slugger->slugify("c'est un test ça alors, lol é è ça");
```

SF2.8 php7.1

**Comment by florianeckerstorfer** [comment]
Can you post your `cocur_slugify` configuration?

**Comment by ibasaw** [comment]
no conf at all

**Comment by florianeckerstorfer** [comment]
Ok, I have a guess why the bug exists. I currently don't have access to my full dev environment, could you try to change lines 42-47 in `CocurSlugifyExtension.php` to:

```php
// Extract slugify arguments from config
$slugifyArguments = array_intersect_key($config, array_flip(['lowercase', 'separator', 'regexp', 'rulesets']));

if (empty($config['rulesets'])) {
    unset($config['rulesets']);
}
```

**Comment by ibasaw** [comment]
not more, same problem

**Comment by florianeckerstorfer** [comment]
Do you encounter this problem in the `production` environment? In that cause you probably need to clear the cache:

```
php app/console cache:clear --env=prod
```

**Comment by ibasaw** [comment]
in dev for now, not tested my site yet in prod

**Comment by florianeckerstorfer** [comment]
Do you have a more precise error message (found in `app/logs/dev.log`)? I just set up a new Symfony 2.8 project with Slugify v3.0.1 and everything worked fine.

**Comment by ibasaw** [comment]
i'm stuck at 2.5 because of sonata core 2.xdev use your bundle at 2.x...

**Comment by florianeckerstorfer** [comment]
Ah ok, The French ruleset has been added in 3.0, but the rules have been part of the general section before. Just remove  the `activateRuleset()`line. The transliteration for `ÿ` and `Ÿ` are missing, but you can add them using custom rules.

Or you can ask Sonata to update to Slugify 3.0
