### ISSUE TITLE
Ability to add a project-specific ruleset

### ISSUE THREAD

**Issue by Alsciende** [cocur/slugify#202]
Hello, I'm using slugify with its Symfony integration, and it works very well (thank you!).

The language I'm transliterating from is a fantasy language, so it's not covered by a bundled ruleset. I can get what I need by using default and some other rulesets, like latvian, but I'd like to craft a ruleset specific to my fantasy language. I figure it would be cleaner and make the service faster.

Is there any way to use a project-specific ruleset currently? Is this a feature you would consider including in your service? Would you accept PR for that?

**Comment by florianeckerstorfer** [comment]
For project-specific rules just add them to the Slugify using `addRule()` or `addRules()`.
