### ISSUE TITLE
Not Symfony 5 compatible

### ISSUE THREAD

**Issue by dant89** [cocur/slugify#234]
The current composer.json values for Symfony packages prevent this project being compatible with Symfony 5.

```
"symfony/config": "~2.4|~3.0|~4.0",
"symfony/dependency-injection": "~2.4|~3.0|~4.0",
"symfony/http-kernel": "~2.4|~3.0|~4.0",
```
To allow for testing `~5.0` could be added to the above three Symfony components which should be all that's needed.

**Comment by florianeckerstorfer** [comment]
@dant89 Could you create a PR for this?
