### ISSUE TITLE
Not Twig 3.0.0 Compatible

### ISSUE THREAD

**Issue by keulinho** [cocur/slugify#235]
The project is currently not Twig 3.0.0 compatible.

The extended global `\Twig_Extension` class doesn't exist anymore.
To add Twig 3.0.0 support it is problably necessary to drop Twig 1 support.

**Comment by mhujer** [comment]
@keulinho See https://github.com/cocur/slugify/pull/236

**Comment by keulinho** [comment]
@florianeckerstorfer with https://github.com/cocur/slugify/pull/236 being merged dev-master is compatible with twig 3.0

is there a timeline when we can expect this being released?

**Comment by florianeckerstorfer** [comment]
@keulinho With #238 being merged this should be fine now. Release will probably happen on the weekend
