### ISSUE TITLE
 Class 'Twig_Extension' not found in Symfony 4.4

### ISSUE THREAD

**Issue by jarekkowol** [cocur/slugify#252]
After upgrade from Symfony 4.3 to 4.4 i have problem with Twig extension.

In SlugifyExtension.php line 26:
Class 'Twig_Extension' not found 

CRITICAL  [php] Uncaught Error: Class 'Twig_Extension' not found ["exception" => Error { …}]

Attempted to load class "Twig_Extension" from the global namespace.  
!!    Did you forget a "use" statement?

**Comment by florianeckerstorfer** [comment]
I think the upgrade from 4.3 to 4.4 upgrades Twig to version 3, which is currently not yet compatible with Slugify. A WIP PR is already there #238 

I hope we can have a new version of Slugify out this week which should fix a few compatibility issues

**Comment by FabienPapet** [comment]
You can still update to Symfony 4.4 by fixing your twig version in your composer.json by running

`composer require twig/twig ~2.0`

**Comment by ZaneCEO** [comment]
Slugify was updated to fix this issue: https://github.com/cocur/slugify/releases/tag/v4.0.0 I can confirm that the fix is effective. We can close this is now.
