### ISSUE TITLE
Generated ruleset different from the json file

### ISSUE THREAD

**Issue by tsantos84** [cocur/slugify#270]
I'm trying to use the slugify component but I'm getting a different replacement for the character `ç` on `portuguese-brazilian` ruleset. 

The generated file (e.g DefaultRuleProvider) has the character `ç` mapping to `ç` whereas the same character in the json file maps to `c`.

**Comment by florianeckerstorfer** [comment]
I'm closing this because this has been open too long and I think it has been fixed in the mean time.
