### ISSUE TITLE
Problem with combining characters

### ISSUE THREAD

**Issue by lostfocus** [cocur/slugify#275]
When trying to debug #274 I ran into a weird-ish problem. I got a string from a source that looked like a "normal" unicode string with two German umlauts, but it turned out to use [Combining Characters](https://en.wikipedia.org/wiki/Combining_character) (This StackOverflow question sent me down the right path in the end: [Strange umlaut encoding on file system](https://stackoverflow.com/questions/33329354/strange-umlaut-encoding-on-file-system))

I'm not too sure if it's within the scope of this library to handle these kinds of characters, but I thought I'd put this information here anyway, in case someone else has the problem.

**Comment by ausi** [comment]
If you have the `intl` extension installed on your system you can use the `Normalizer` class to fix that issue:

```php
$this->slugify->slugify(
	\Normalizer::normalize(
		"Erla\xCC\x88uterungsbroschu\xCC\x88re"
	)
);
```

**Comment by florianeckerstorfer** [comment]
@lostfocus Interesting. I think it should be possible to add the German umlauts with combining characters to the ruleset and it should work. But I have not tried that out.
