### ISSUE TITLE
User Deprecated

### ISSUE THREAD

**Issue by Evgeny1973** [cocur/slugify#298]
Can you update, please? 
Symfony 5.4, Slugify 4.0.0

`User Deprecated: Method "Symfony\Component\HttpKernel\Bundle\Bundle::getContainerExtension()" might add "?ExtensionInterface" as a native return type declaration in the future. Do the same in child class "Cocur\Slugify\Bridge\Symfony\CocurSlugifyBundle" now to avoid errors or add an explicit @return annotation to suppress this message.`

**Comment by GromNaN** [comment]
Should be fixed. 
https://github.com/cocur/slugify/pull/299

**Comment by ph-il** [comment]
Is there's a date for a new version?

**Comment by ZaneCEO** [comment]
The last release is from December 2019, so I'm not really sure what to expect.

Meanwhile, I change to `"cocur/slugify": "dev-master",` in my `composer.json` and the issue is fixed. I hope to switch back soon, but for now, it works.

**Comment by florianeckerstorfer** [comment]
I was travelling over Christmas and New Years and started to work on my OSS projects again this week. I hope I can get a new version out this weekend.

**Comment by florianeckerstorfer** [comment]
Released v4.1.0
