### ISSUE TITLE
Issue with usage, example doesnt work after installing with composer

### ISSUE THREAD

**Issue by petrk94** [cocur/slugify#302]
Hello,
Im facing an, hopefully easy to solve issue, but I really dont know what the problem is.
Im using the example of the github repository, the first one and installed it in the parent directory now using in the same directory the test.php file and its telling me

> PHP Fatal error:  Uncaught Error: Class 'Cocur\Slugify\Slugify' not found

Attached a screenshot, hopefully someone can help.
Im using PHP 7.4

![image](https://user-images.githubusercontent.com/19719052/151772361-d9934f6b-65a8-45b9-a3f4-b61fb4e933ee.png)

**Comment by florianeckerstorfer** [comment]
If you use this example with Composer do you have auto-loading enabled?

**Comment by kktsvetkov** [comment]
@petrk94 You need to include the composer beforehand 
```php 
require '/vendor/autoload.php';

use Cocur\Slugify\Slugify;

$slugify = new Slugify();
echo $slugify->slugify('Hello World!'); // hello-world
```

**Comment by petrk94** [comment]
Shame on me, thank you, I totally forgot that^^
