### ISSUE TITLE
Syntax error, unexpected '|', expecting variable {t_variable}

### ISSUE THREAD

**Issue by deyan-ardi** [cocur/slugify#334]
![gambar](https://github.com/cocur/slugify/assets/60816261/f3ab2205-83bf-4d43-b108-2ccfef64f014)
I have some error in my production app, and this because new update of this package.

So what can i do?

**Comment by galanis-a** [comment]
I am guessing you are on php 7.4. You need to downgrade to version 4.3.0 of cocur/slugify. They removed compatibility with PHP 7 in version 4.4 but added back in version 4.5.....

**Comment by deyan-ardi** [comment]
> I am guessing you are on php 7.4. You need to downgrade to version 4.3.0 of cocur/slugify. They removed compatibility with PHP 7 in version 4.4 but added back in version 4.5.....

Thanks your information, i will try later...
