### ISSUE TITLE
Please update for Symfony > 7

### ISSUE THREAD

**Issue by Evgeny1973** [cocur/slugify#338]
The **"Symfony\Component\HttpKernel\DependencyInjection\Extension"** class is considered internal since Symfony 7.1, to be deprecated in 8.1; use Symfony\Component\DependencyInjection\Extension\Extension instead. It may change without further notice. You should not use it from **"Cocur\Slugify\Bridge\Symfony\CocurSlugifyExtension"**.

**Comment by rakshitbharat** [comment]
I suggest lock your project all dependency,
almost all PHP projects are not stable nowadays and even not frequently updated.

**Comment by Evgeny1973** [comment]
> I suggest lock your project all dependency, almost all PHP projects are not stable nowadays and even not frequently updated.

Symfony is updated, php is updated, and you suggest sitting on old versions. This is the wrong solution to the question.

**Comment by florianeckerstorfer** [comment]
@Evgeny1973 Please submit a PR
