### ISSUE TITLE
Japanese support

### ISSUE THREAD

**Issue by dmyers** [cocur/slugify#46]
Is there a way to get Japanese characters to work?

**Comment by picks44** [comment]
+1 for the addition of the Japanese

**Comment by xoco70** [comment]
+1 for the addition of the Japanese

**Comment by SuN-80** [comment]
I gave it a try some months ago and it's more complicated to implement than Chinese. But I've stopped working on this because nobody was able help me understand why my Chinese pull request failed 2 checks, while it works perfectly (#158).

**Comment by wandersonwhcr** [comment]
Please, can you rebase your branch to `master`?

**Comment by EraYaN** [comment]
Something like
```
transliterator_transliterate("Any-Latin; NFD; [:Nonspacing Mark:] Remove; NFC; [:Punctuation:] Remove; Lower();", $string)
```

Already transliterates some Japanese, although kanji is still very much an issue, It seem to just take the first reading it can find.

A better option would probably be something like MeCab.

Some example implementations:
https://github.com/MikimotoH/furigana
https://ankiweb.net/shared/info/3918629684

It does add a C++ dependency: https://github.com/taku910/mecab
There seem some PHP binding projects like this: https://github.com/rsky/php-mecab

This could do a runtime check and keep current behaviour if it is not available, and enable it when mecab is available.

**Comment by DemigodCode** [comment]
I think that issue can be closed.
