### ISSUE TITLE
Feature request: getRules() method

### ISSUE THREAD

**Issue by GDmac** [cocur/slugify#65]
We (try to) use slugify, next to url-slugs, to also create "safe" filenames and some titles, which allow uppercase characters. The slugify rules already have conversions for uppercase, like "Ö" => "O", but these are discarded with two ``strtolower()`` calls.

- Can we have access to the protected rules by implementing a getRules() method, 
  so that i can do my own ``strtr($str, $slugify->getRules())`` conversions based on slugify,
  when i need to keep uppercase characters.
```php
    public function getRules()
    {
        return $this->rules;
    }
```
- Alternatively suggestion, have an extra $strict=true parameter on slugify()
  to allow more control over uppercase conversion.
```php
    public function slugify($string, $separator = '-', $strict = true)
    {
        $string = strtr($string, $this->rules);
        if ($strict) $string = strtolower($string);
        $string = preg_replace($this->regExp, $separator, $string);
        if ($strict) $string = strtolower($string);

        return trim($string, $separator);
    }

    // ...

    $in = "Et le proxénète s'est avancé, à la Barre";
    $var = $slugify->slugify($in);
    // et-le-proxenete-s-est-avance-a-la-barre

    // also allow uppercase, spaces and some chars, remove others
    $slugify->setRegExp('/[^a-zA-Z0-9_., -]+/');
    $var = $slugify->slugify($in, '', false);
    // Et le proxenete sest avance, a la Barre
```

**Comment by florianeckerstorfer** [comment]
I don't like the idea of a `getRules()` method, but we could add an option to disable the conversion to lowercase. However, I would add the option to the constructor, not the `slugify()` method.

**Comment by GDmac** [comment]
Thanks for the options, but sadly this won't work for Silex (Bridge) nor for Slugify::create()

**Comment by GDmac** [comment]
When using slugify as a service-provider, there would be a need to be able to ``setOptions()`` later on.
