### ISSUE TITLE
Turkish and German characters Problem

### ISSUE THREAD

**Issue by emnsen** [cocur/slugify#74]
- German:
  - Ö => OE
  - Ü => UE
  - ö => oe
  - ü => üe

- Turkish:
  - Ö => O
  - Ü => U
  - ö => o
  - ü => u

How to solve this problem ? 

Example;

- "Öğretmen" the Turkish word:
  - Öğretmen => oegretmen this convert false
  - Öğretmen => ogretmen this convert true

**Comment by emnsen** [comment]
Aaa.. sorry this issue open #56 please close my issue.

**Comment by florianeckerstorfer** [comment]
Currently you need to manually add the rules for Turkish. I hope we can solve this problem in the future.

By the way, you can close your own issues.
