### ISSUE TITLE
Minimum PHP version 5.5.9

### ISSUE THREAD

**Issue by choonge** [cocur/slugify#79]
In https://github.com/cocur/slugify/commit/77e3f225a843d3d4a47445680671a27557d07d80 , the minimum PHP version was set to 5.5.9. We're having trouble now because all our production servers are running CentOS with 5.4.*.

Is there any chance that can be reverted?

**Comment by mac2000** [comment]
The core slugify itself should work fine on early PHP versions

**Comment by florianeckerstorfer** [comment]
PHP 5.4 support has ended in September and we need to move on. Please use 1.4.x if you really need to use PHP 5.4 (but you should upgrade as soon as possible). I will merge bugfixes into the 1.4 branch.

**Comment by florianeckerstorfer** [comment]
After thinking about this a little bit more, I will probably tag the version requiring PHP 5.5+ with 2.0. That way every package that depends on Slugify and correctly defined the 1.0 branch will not break.

**Comment by choonge** [comment]
Thanks, sounds good!
