### ISSUE TITLE
Compatibility with Symfony 3.0?

### ISSUE THREAD

**Issue by bibeksigdel33** [cocur/slugify#92]
Is this library compatible with php symfony 3.0 .

**Comment by sfgn** [comment]
I can't comment for the author of course, but I'm using it on a SF3 project with no issues encountered.

**Comment by florianeckerstorfer** [comment]
Yes, Slugify is compatible with Symfony 3.0. I will update `composer.json` to include both the 2.x and the 3.x branch, that way Travis will test the library against both versions.
