### ISSUE TITLE
1.4.1 should be tagged 2.0

### ISSUE THREAD

**Issue by GawainLynch** [cocur/slugify#94]
This [change was merged](https://github.com/cocur/slugify/commit/bd1cc47245805c530c97a8420c0d8fb99a71ed80) in November last year into your `2.0` branch… then the [2.0 branch was merged into master](https://github.com/cocur/slugify/commit/7534f95908bc493e13e5823a1b0626f2e3cbf7d2) soon after.

These changes, while awesome, break BC and Composer is pulling this in for Bolt users where our require is `^1.0`. :wink:

**Comment by florianeckerstorfer** [comment]
Damn, I created the tag from the wrong branch. This should be fixed now. Does it work for Bolt now?

**Comment by GawainLynch** [comment]
Just re-running Travis now… but looking at the tagged branch I would say so.

I'll close now, with many thanks, and update if there is some weird unforeseen problem!

P.S. Looking forward to 2.0 from you all :+1:

**Comment by florianeckerstorfer** [comment]
Great. Sorry, for messing this up. If there are any other problems please reopen this or create another issue.

**Comment by GawainLynch** [comment]
@florianeckerstorfer Just one thing I have noticed, [Packagist hasn't gotten the "new" tag](https://packagist.org/packages/cocur/slugify#v1.4.1):

```
v1.4.1 2016-02-11 09:44 UTC
requires
php: >=5.6

requires (dev)
phpunit/phpunit: ~5.1.3
mockery/mockery: ~0.9
mikey179/vfsstream: ~1.6
symfony/http-kernel: ~2.4|~3.0
symfony/dependency-injection: ~2.4|~3.0
twig/twig: ~1.12
silex/silex: ~1.3
pimple/pimple: ~1.1
zendframework/zend-modulemanager: ~2.2
zendframework/zend-view: ~2.2
zendframework/zend-servicemanager: ~2.2
laravel/framework: ~5.1
nette/di: ~2.2
latte/latte: ~2.2
plumphp/plum: ~0.1
```

**Comment by florianeckerstorfer** [comment]
I did a force update on Packagist, everything should be up-to-date now.

**Comment by GawainLynch** [comment]
That looks to have gotten it… Thank you!
