### ISSUE TITLE
Feedback for 2.0 release

### ISSUE THREAD

**Issue by florianeckerstorfer** [cocur/slugify#95]
I want to release 2.0 pretty soon but I would like to gather some feedback before. Please let me know if you already use the 2.0 (that is, the master branch) in your code or if you tried to use it and it didn't work out.

I am especially interested in the various integrations. Tests are one thing, using it in real world code another one and I don't have time (and, frankly, expertise for some of the integrations) to test them in real examples.

Any help to get 2.0 out of the door is highly appreciated.

**Comment by GawainLynch** [comment]
Having only quickly messed around… porting our project was relatively straightforward. :+1: 

Out one blocker for *our* upcoming major version bump would be the requirement of `PHP >= 5.6`. 

Silex, Symfony and us have all gone for `>= 5.5.9` (I would love to have followed @Seldaek's charge with Monolog and gone for PHP 7+, but… real life), so would this make sense to follow suit on?

**Comment by florianeckerstorfer** [comment]
I set the minimum version to 5.5.9, so that should work out now

**Comment by GawainLynch** [comment]
Wonderful, thank you.
