### ISSUE TITLE
Version 1.4.1

### ISSUE THREAD

**Issue by nino-s** [cocur/slugify#96]
Does your newest release tag refer to the correct commit?

Current: 16cdd7e792657d524cde931ea666436623b23301
Master merge: 5b9c427e09d5b14587b9c5d0643a8e61d05fe2e1

With v1.4.1 - referring to 16cdd7e - i get errors which i dont get with the master merge. (`preg_replace(): Delimiter must not be alphanumeric or backslash at Slugify.php:804`)

**Comment by florianeckerstorfer** [comment]
That is weird, when I check out the v1.4.1 branch everything works fine and I use v1.4.1 in some of my projects and everything is fine. I made a mistake when releasing v1.4.1 and initially created the tag from the master (that is 2.0) branch. I later deleted the tag and created it from the correct 1.4 branch. Could you manually remove the `vendor/cocur/slugify` directory and update using Composer again?

**Comment by florianeckerstorfer** [comment]
I am closing this, if you still have problems please reopen this issue.
