### ISSUE TITLE
Empty regexp error when using option "lowercase" to false

### ISSUE THREAD

**Issue by adadgio** [cocur/slugify#99]
When specifiying the lowercase option

```
$slugify = new Slugify(array('lowercase' => false)); // keep uppercase letters
$this->name = $slugify->slugify("Annonce: Jean Claude vends dame", '_');
```

An error is thrown:

`Warning: preg_replace(): Empty regular expression`

Specifying a regexp as second option does not fix the issue either.

**Comment by florianeckerstorfer** [comment]
Which version or branch are you using? Because there is a test and it passes for the `master` branch.

**Comment by adadgio** [comment]
I'm using release 1.4. It doesn't pass unit tests according the git... ;-)

**Comment by florianeckerstorfer** [comment]
According to Travis the 1.4 branch does work. (see https://travis-ci.org/cocur/slugify/builds/111551117)

I also tested it out on my machine and I can't reproduce the error. Which PHP version are you using?

**Comment by adadgio** [comment]
PHP 5.6.16

**Comment by florianeckerstorfer** [comment]
The AppVeyor tests failed. In this case AppVeyor failed because the setup of PHP on the windows machine didn't work.

**Comment by florianeckerstorfer** [comment]
I am closing this, if the problem persists please reopen.
